name: fe_sektak
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.25+3
  geolocator: ^5.3.0
  splashscreen: ^1.2.0
  toast: ^0.1.5
  connection_status_bar: ^1.1.2
  flutter_icons: ^1.0.0+1
  google_fonts: ^1.0.0
  flutter_datetime_picker: ^1.3.5
  numberpicker: ^1.2.0
#  camera: ^0.5.7+4
#  path_provider: ^0.5.0
#  video_player: ^0.10.0
#  pedantic: ^1.8.0
#  image_gallery: ^1.2.0
  pusher_websocket_flutter: ^0.1.1
  shared_preferences: ^0.5.7
  image_picker: ^0.6.5
  flutter_mobile_vision: ^0.1.4+1
  dio: ^3.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - assets/images/
